version: "3.8"

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    container_name: nginx-rp

  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: backend-db
    volumes:
      - ./database:/var/lib/postgresql/data

  frontend:
    image: example-frontend:v2
    ports:
      - 5000:5000
    depends_on:
      - backend

  backend:
    image: example-backend:v2
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=backend-db  # Specify the correct hostname or use the container name
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db

  redis:
    image: "redis"
