version: "3.8"

services:
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=example
    container_name: backend-db

  frontend:
    image: "example-frontend"
    ports:
      - 5000:5000

  backend:
    image: "example-backend"
    ports:
      - 8080:8080
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_HOST=backend-db  # Specify the correct hostname or use the container name
      - POSTGRES_USER=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - db

  redis:
    image: "redis"
