version: '3.8'

services:

  frontend-uh:
    image: vidalme/frontend-uh
    ports: 
      - 5000:5000
    container_name: frontend-uh-c

  backend-uh:
    image: vidalme/backend-uh
    ports:
      - 8080:8080
    container_name: backend-uh-c
  
