version: "3.8"

services:
  frontend:
    image: "example-frontend"
    ports:
      - 5000:5000

  backend:
    image: "example-backend"
    ports:
      - 8080:8080
    build: ~/projects/docker-helsinki-university/my_notes/ex-1.13/example-backend
  
  redis:
    image: "redis"
