  version: '3.8'

  services:

    db:
      image: postgres
      restart: unless-stopped
      container_name: backend-db
      environment:
        POSTGRES_PASSWORD: pg

    frontend-uh:
      image: vidalme/frontend-uh
      ports: 
        - 5000:5000
      container_name: frontend-uh-c

    backend-uh:
      image: vidalme/backend-uh
      ports:
        - 8080:8080
      container_name: backend-uh-c
      environment:
        - POSTGRES_PASSWORD=pg
        - POSTGRES_HOST=db 
        # - POSTGRES_USER=postgres
        # - POSTGRES_DATABASE=postgres
      depends_on:
        - db

    redis_se:
      image: redis:7.2.4
      container_name: redisco
      volumes:
        - ./data:/data
