  version: '3.8'

  services:
      
    nginx:
      image: nginx
      ports: 
        - 80:80
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    db:
      image: postgres
      restart: unless-stopped
      environment:
        POSTGRES_PASSWORD: pg
      
      volumes:
        - type: bind
          source: ./database
          target: /var/lib/postgresql/data

    frontend-uh:
      image: vidalme/frontend-uh
      ports: 
        - 5000:5000
      container_name: frontend-uh

    backend-uh:
      image: vidalme/backend-uh
      ports:
        - 8080:8080
      container_name: backend-uh
      environment:
        - POSTGRES_PASSWORD=pg
        - POSTGRES_HOST=db 
        # - POSTGRES_USER=postgres
        # - POSTGRES_DATABASE=postgres
      depends_on:
        - db

    redis_se:
      image: redis:7.2.4
      volumes:
        - ./data:/data
