version: '3.8'

services:
      
  nginx:
    image: nginx
    ports: 
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend-uh

  db:
    image: postgres
    restart: unless-stopped
    container_name: backend-db
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data

  frontend-uh:
    build:
      context: ../ex-1.12/example-frontend
    # ports: 
      # - 5000:5000 
    container_name: frontend-uh
    depends_on:
      - backend-uh
    environment:
      - REACT_APP_BACKEND_URL=${REACT_APP_BACKEND_URL}

  backend-uh:
    build:
      context: ../ex-1.13/example-backend
    # ports: 
      # - 8080:8080
    environment:
      - REQUEST_ORIGIN=${REQUEST_ORIGIN}
      - REDIS_HOST=${REDIS_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}  
    container_name: backend-uh
    depends_on: 
      - db

  redis:
    image: redis:7.2.4
    container_name: redis
    volumes:
      - ./data:/data 
