version: '3.8'

services:

  frontend-uh:
    build:
      context: ../ex-1.12/example-frontend
    ports: 
      - 5000:5000
    container_name: frontend-uh

  backend-uh:
    build:
      context: ../ex-1.13/example-backend
    ports: 
      - 8080:8080
    environment:
      - REQUEST_ORIGIN=${REQUEST_ORIGIN}
      - REDIS_HOST=${REDIS_HOST}
    container_name: backend-uh

  redis:
    image: redis:7.2.4
    container_name: redis
    volumes:
      - ./data:/data